# Generated by Django 5.0.1 on 2024-03-24 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_details', '0004_indiacities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
